### ISSUE TITLE
eigen3 related UnalignedArrayAssert crash on melodic with AMD64 machine

### ISSUE THREAD

**Issue by Eric97** [cartographer-project/cartographer_ros#1466]
Hello,

Encounterred seg fault when running `roslaunch cartographer_ros demo_backpack_2d.launch bag_filename:=${HOME}/Downloads/cartographer_paper_deutsches_museum.bag`

Environments:
- Ubuntu 18.04 with ROS melodic
- AMD64 machine
- latest master on `cartographer`
- latest master on `cartographer_ros` 
- latest master on `ceres-solver`
- eigen3 3.3.7 (tried default 3.3.4 version, also same error)

A core dump as below:

> #3  0x00007ffff2168412 in __GI___assert_fail (
>     assertion=0x555555d99580 "(internal::UIntPtr(eigen_unaligned_array_assert_workaround_gcc47(array)) & (31)) == 0 && \"this assertion is explained here: \" \"http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html"...,
>     file=0x555555d99548 "/usr/include/eigen3/Eigen/src/Core/DenseStorage.h", line=128,
>     function=0x555555d9e920 <Eigen::internal::plain_array<double, 4, 0, 32>::plain_array()::__PRETTY_FUNCTION__> "Eigen::internal::plain_array<T, Size, MatrixOrArrayOptions, 32>::plain_array() [with T = double; int Size = 4; int MatrixOrArrayOptions = 0]") at assert.c:101
> #4  0x0000555555912cd7 in Eigen::internal::plain_array<double, 4, 0, 32>::plain_array (this=0x555556154650)
>     at /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:128
> #5  0x0000555555908460 in Eigen::DenseStorage<double, 4, 4, 1, 0>::DenseStorage (this=0x555556154650)
>     at /usr/include/eigen3/Eigen/src/Core/DenseStorage.h:187
> #6  0x00005555558ff12c in Eigen::PlainObjectBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >::PlainObjectBase (this=0x555556154650)
>     at /usr/include/eigen3/Eigen/src/Core/PlainObjectBase.h:484
> #7  0x00005555558f62d8 in Eigen::Matrix<double, 4, 1, 0, 4, 1>::Matrix (
>     this=0x555556154650, x=@0x7fffffffb7f0: 0, y=@0x7fffffffb7f8: 0,
>     z=@0x7fffffffb800: 0, w=@0x7fffffffb7e8: 1)
>     at /usr/include/eigen3/Eigen/src/Core/Matrix.h:358
> #8  0x00005555558ee255 in Eigen::Quaternion<double, 0>::Quaternion (
>     this=0x555556154650, w=@0x7fffffffb7e8: 1, x=@0x7fffffffb7f0: 0,
>     y=@0x7fffffffb7f8: 0, z=@0x7fffffffb800: 0)
>     at /usr/include/eigen3/Eigen/src/Geometry/Quaternion.h:251
> #9  0x0000555555960f48 in Eigen::QuaternionBase<Eigen::Quaternion<double, 0> >::Identity () at /usr/include/eigen3/Eigen/src/Geometry/Quaternion.h:106
> #10 0x000055555596c2ed in cartographer::transform::Rigid3<double>::Rigid3 (
>     this=0x555556154630)
>     at /home/eric/cartographer/cartographer/transform/rigid_transform.h:123
> #11 0x0000555555980c9b in cartographer_ros::MapBuilderBridge::LocalTrajectoryData::LocalTrajectoryData (this=0x555556154610)
>     at /home/eric/ws_agv/src/cartographer_ros/cartographer_ros/cartographer_ros/map_builder_bridge.h:52

Seems like a compatibility issue with other packages, but no ideas where to proceed. 

Regards,
Eric

**Comment by Eric97** [comment]
Thanks for the info.
Unfortunately, I didn't figure out a way to solve this bug. Recompile and install on a fresh ubuntu 18.04 works perfect. Maybe it is just a corner case on my machine. Will close this issue.
